# Generated by Django 4.1.6 on 2023-02-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csfd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loaded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("init_load", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["movie_name"]},
        ),
    ]
