# Generated by Django 4.1.6 on 2023-02-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csfd", "0002_loaded_alter_actor_options_alter_movie_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="unaccent_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="movie",
            name="unaccent_movie_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
